---
name: Release

on:
  push:
    branches: [master, alpha, beta]

# Only allow one release workflow to execute at a time, since each release
# workflow uses shared resources (git tags, package registries)
concurrency:
  group: ${{ github.workflow }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: EricCrosson/semantic-release-your-github-action@v2
